[project]
name = "job-scraper"
packages = ["src"]
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiokafka>=0.12.0",
    "bs4>=0.0.2",
    "celery>=5.5.3",
    "httpx>=0.28.1",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "pymongo>=4.15.3",
    "redis>=7.0.1",
]

[tool.uv.workspace]
members = [
    "kafka_setup",
]
